# Generated by Django 2.2.6 on 2019-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.TextField()),
            ],
        ),
    ]
